name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run-script lint
      - name: Test
        run: npm run-script test
